aws:
  region: eu-west-2
  auth:
    - type: profile
      path: ~/.aws/credentials
      profile: prod
cur:
  bucket: cost-reports
  prefix: cur/year=2025/
  region: eu-west-2      # override bucket region
  schedule: "0 1 * * *"  # daily at 01:00 UTC