aws:
  region: ap-southeast-1
  auth:
    - type: credentials
      accessKeyID: AKID123
      secretKey: SK123
    - type: iam
      role-to-assume: arn:aws:iam::123456789012:role/CURLoaderRole
cur:
  bucket: aws-cur-bucket
  prefix: cur/
  schedule: "30 4 * * *"