# .github/workflows/ci.yml
name: CI

on:
  push:    # runs on push to any branch
    paths:
      - '**'
  pull_request:  # runs on PRs targeting any branch
    paths:
      - '**'

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run gofmt
        run: go fmt ./...

      - name: Run govet
        run: go vet ./...

      - name: Run tests
        run: go test ./... -cover

  secret-scan:
    name: Secret Scan
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scan for secrets with TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.16.0
        with:
          path: '.'
          base: ${{ github.event.pull_request.base.ref || github.event.repository.default_branch }}
          head: ${{ github.sha }}
