# .github/workflows/ci.yml
name: CI

on:
  push:    # runs on push to any branch
    paths:
      - '**'
  pull_request:  # runs on PRs targeting any branch
    paths:
      - '**'

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run gofmt
        run: go fmt ./...

      - name: Run govet
        run: go vet ./...

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b "$(go env GOPATH)"/bin v1.53.0

      - name: Run golangci-lint
        run: golangci-lint run

      - name: Run tests
        run: go test ./... -cover

  secret-scan:
    name: Secret Scan
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scan for secrets
        uses: trufflesecurity/secret-scan-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths: |
            .
          exclude_paths: |
            **/test_data/**

  generate-docs:
    name: Generate Go Docs
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install gomarkdoc
        run: go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest

      - name: Generate docs for key packages
        run: |
          mkdir -p docs
          gomarkdoc ./internal/config > docs/config.md
          gomarkdoc ./internal/aws    > docs/